### ISSUE TITLE
Bazel build fails

### ISSUE THREAD

**Issue by kdt3rd** [AcademySoftwareFoundation/openexr#1075]
I am starting to receive messages saying the bazel build is failing, both in my fork and from the main repo (upon PR push). Is there a reason this is enabled at all?

**Comment by meshula** [comment]
It was to get early warnings of issues. @Vertexwahn, any thoughts?

**Comment by Vertexwahn** [comment]
There was a Bazel build problem on `master` which I introduced by accident with PR 1068. It was fixed with PR 1070.

![image](https://user-images.githubusercontent.com/3775001/124296127-e8d86480-db59-11eb-853b-23a5fc5c626b.png)

Do you see the problem still on any other branches? 

For me, this issue seems to be fixed. Please let me know if Bazel Build makes anywhere a problem.
