### ISSUE TITLE
Replace `uint64_t` (etc.) with `uint_least64_t` (etc.)

### ISSUE THREAD

**Issue by c-lipka** [AcademySoftwareFoundation/openexr#1081]
Using `intN_t` and `uintN_t` types is a questionable habit, as even modern C++ standards do not guarantee their availability. Using `int_leastN_t` / `uint_leastN_t` instead (or, internally, `uint_fastN_t` where speed is of more concern than memory footprint) is generally a better choice.

On platforms that do support `intN_t` and `uintN_t`, those types are identical to the corresponding `int_leastN_t` and `uint_leastN_t`, so changing the types should not cause any backward compatibility problems.

**Comment by lgritz** [comment]
https://en.cppreference.com/w/cpp/types/integer

https://cplusplus.github.io/LWG/issue2820

While it's true that the C++ standard says these don't need to be defined if the underlying width is not natively available, that is not the case for any of the hardware or compiler combinations that we support.

The "leastN" types are not appropriate to use in this case because we really and truly do mean for these to be specific sizes. It's not ok for the compiler implementation to choose something bigger.

If these types are not available, the software will not build, and I think that's the correct result. If a particular data type in the OpenEXR files needs to be 32 bits wide, say, and we are somehow on a platform that doesn't have any 32-bit wide integer types, we have a whole lot of trouble. Even more problems would result from the compiler silently using a different sized data type.

**Comment by meshula** [comment]
The common practice on microcontrollers and other tiny systems without wide integers is to use a restricted special case library to read and write a small subset of exr from the microcontroller, and do further processing on a bigger box with the full library. As an example, https://github.com/syoyo/tinyexr attempts to work with compiler native types, and has compile time checks if the required bit widths can't be satisfied on the target platform. It doesn't support any of the sophisticated features of exr, but in typical microcontroller applications the important thing is the packaging of hdr image data, not creating fancy layered images.

**Comment by meshula** [comment]
@c-lipka Do those answers answer your question? Or are there specific cases beyond the hard requirements Larry mentioned that you might have in mind?
