### ISSUE TITLE
Need proper handling of intrinsic headers on Windows

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#1114]
Now that ARM64 macOS builds properly, can we confirm that we're doing the right thing for WIN32?  @patlefort suggests the following:

```
#ifdef __has_include
#    if defined(_WIN32) && __has_include(<intrin.h>)
#        include <intrin.h>
#    elif defined(__x86_64__) && __has_include(<x86intrin.h>)
#        include <x86intrin.h>
#    endif
#endif
```

Was this in response to a build failure? @meshula, does this look right to you?

**Comment by meshula** [comment]
I just did a build from top of tree on WSL, targeting Ubuntu on windows. That worked fine. I did a build on Windows 10, using VS2019, that worked fine. I'm not set up to do mingw builds which can target mingw or windows native, so I didn't test that.

Unless someone who uses mingw has feedback, I think we should leave the macros as they are until we get that feedback.

**Comment by patlefort** [comment]
I use mingw to cross-compile to win32 on linux and it work. It's part of why I made the proposition. Unfortunately checking for the presence of files is insufficient in this case as some platform pretend to have things they don't. The order is also important, the `_WIN32` check has to be first because mingw has both `__x86_64__` and `_WIN32` but you want `intrin.h`. I don't know a platform who would want the opposite.

**Comment by kdt3rd** [comment]
yes, the has_include check was over optimistic thinking on my part, and while the extra check for existence is nice, it probably isn't necessary, in that those files will most likely always exist, so we could probably simplify the proposal

**Comment by meshula** [comment]
Just poking around on various machines... seems like both files are _win32 only, so are we converging on the snip below?

(At least find /usr/include -name x86intrin.h doesn't find anything on my CentOS machine, nor does the equivalent in the mac Platform SDK).

```cpp
#ifdef _WIN32
#    include <intrin.h>
#    if defined(__x86_64__)
#        include <x86intrin.h>
#    endif
#endif
```

**Comment by patlefort** [comment]
That's because `x86intrin.h` is somewhere in `/lib/gcc` and also in `/lib/clang` if you have clang. It's a GCC thing and clang can emulate both gcc or msvc. Clang will pretend to be gcc on linux and msvc on windows which is why it has both files. Also, yes, the `__has_include` is probably unnecessary. I think checking for the presence of `__GNUC__` would be more accurate:

```c
#ifdef _WIN32
#    include <intrin.h>
#elif defined(__GNUC__)
#    include <x86intrin.h>
#endif
```

**Comment by meshula** [comment]
Thanks for the pointer, I found them on CentOS in /usr/lib/gcc.

**Comment by kthurston** [comment]
yeah, x86intrin is also for linux, but it can't be `__GNUC__` - it needs to be x86 (i.e. arm linux doesn't have this)

**Comment by patlefort** [comment]
So maybe it should check for both `__GNUC__` and `__x86_64__`. Although `__x86_64__` would be sufficient, I feel it's safer and clearer to also check for `__GNUC__`. However you see fit.

**Comment by cary-ilm** [comment]
Look at #1117, I think that's the conclusion. @meshula and @kdt3rd, do you think it's best to include the check for __GNU__ as well?

**Comment by kthurston** [comment]
put a comment on your PR, I do not think we should include GNUC, but we may want to consider some of the other x86 #defines to pick up ICC or other compilers?
