### ISSUE TITLE
Example to write HALF float luminance pixels into .exr

### ISSUE THREAD

**Issue by Realitian** [AcademySoftwareFoundation/openexr#1179]
Hi,

I am beginner of openexr.
I need to write HALF float pixels for single luminance channel into .exr image.
I tried to seek the example for that, but I couldn't find.
Can anyone share that example here?

**Comment by peterhillman** [comment]
There is a similar example in the documentation here:
https://openexr.readthedocs.io/en/latest/ReadingAndWritingImageFiles.html#using-the-general-interface-for-scan-line-based-files.
(also https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/examples/generalInterfaceExamples.cpp#L35)

In your case, the half float channel should be called "Y" instead of "G" to indicate it is luminance, and you don't need the two lines that refer to the "Z" channel.

**Comment by Realitian** [comment]
Great, it works!
Thank you!!!
