### ISSUE TITLE
/usr/bin/ld: cannot find -lIlmImf and -lHalf

### ISSUE THREAD

**Issue by fu123456** [AcademySoftwareFoundation/openexr#1231]
Hi. I have install openexr already from the source code without any error. However, I use this lib to compile other sources such as https://github.com/skycaptain/openexr-matlab, I have an error: /usr/bin/ld: cannot find -lIlmImf and -lHalf. In the libs from openexr, I do not find any *.so file related with Half and llmlmf. So how to generate the corresponding so files and solve my issue. Very thanks.

**Comment by lgritz** [comment]
For the last two major releases of OpenEXR, there has been no libIlmImf or libHalf. The libraries are now libOpenEXR (for the file handling stuff) and libImath (for the mathy stuff, including the 'half' type). So you might be ok if you just change it to `-lOpenEXR -lImath`.

So this is actually a bug in the openexr-matlab project -- which is not in any way affiliated with the actual OpenEXR project here! -- where they have not kept up with changes in the current OpenEXR project. In fact, visiting https://github.com/skycaptain/openexr-matlab, I see that it's "archived", which means nobody is actively maintaining or updating it.

**Comment by lgritz** [comment]
If you build OpenEXR from a tag corresponding to release 2.5 or earlier, it will have the library names as you expected originally. (But of course, it will not have any of the fixes or improvements from the last 2-3 years of development.)

**Comment by fu123456** [comment]
My system is Manjaro (Archlinux). For Imath, I install it by 'yaourt -Sy imath' and 'yaourt -Sy lib32-imath', and I replaced '-lIlmImf ' and '-lHalf' with '-lOpenEXR' and '-Imath'. But, I also have some errors:
![my_issue3](https://user-images.githubusercontent.com/22411577/154187301-cabf37c3-b34f-4b8d-8b8b-8db1f832356b.png)

**Comment by fu123456** [comment]
It does work with using openexr2.5.0. Thanks.

**Comment by lgritz** [comment]
In retrospect, it doesn't surprise me that there was still trouble. You asked "what do I say instead of `-lIlmImf`?" and I naively answered only that specific question. But in reality, there is more to converting a project that was written for OpenEXR 2.x to be able to use 3.x (at the very least, some header includes need to change). The openexr-matlab project -- which as I said is not in any way affiliated with the OpenEXR project -- has not been modified in many years, so obviously has none of the necessary changes that would allow it to build against a modern OpenEXR+Imath.
