### ISSUE TITLE
openexr is based on Imath, rather than ilmbase any more?

### ISSUE THREAD

**Issue by jiapei100** [AcademySoftwareFoundation/openexr#1313]
Does openexr still rely on ilmbase???

**Comment by lgritz** [comment]
IlmBase (which was actually several libraries) was always *part* of the OpenEXR project. Some distros split it up into two packages.

Since 3.0, the OpenEXR project itself split into "openexr" and "imath" repos. Some of what used to be in IlmBase is now imath, other parts have merged into the openexr part. Modern OpenEXR does depend on Imath. "IlmBase" hasn't been a thing at all since OpenEXR 2.x, years ago now.

**Comment by jiapei100** [comment]
@lgritz 
Thank you very much for your clarification ...
