### ISSUE TITLE
I don't know how to install OpenEXR

### ISSUE THREAD

**Issue by lor3ny** [AcademySoftwareFoundation/openexr#1442]
I am a student and I am trying to optimize my thesis project using C++. I was able to import OpenCV and other libraries but not OpenEXR. The project is set up on Visual Studio Community. What are the steps to follow to properly install OpenEXR and related dependencies such as Imath?

Thank you for any kind of help, sorry but I am still learning.

**Comment by meshula** [comment]
Perhaps the place to start is to follow the instructions here ~ https://openexr.com/en/latest/install.html#install ~ and if you encounter difficulties we can answer questions here.

**Comment by lor3ny** [comment]
I followed the instructions on the official page.
I downloaded the repo and opened it on VS Community. As soon as I opened VS Community, CMake started generation operations and created a folder:

`openexr\out\build\x64-Debug`

The contents of the folder are as follows:

![x64-Debug 01_06_2023 21_35_48](https://github.com/AcademySoftwareFoundation/openexr/assets/54499060/db5f5a77-ff73-4d30-9bcd-3e435435c13d)

I can't go on from here.

**Comment by meshula** [comment]
You're going to need to do a command line build, not from the CMake GUI or visual studio.

The first thing you need to do is to find the Visual Studio command shell, not the regular command shell, and not the Terminal program.

It's in the Windows applications menu and it is called:

`Visual Studio 2022\x64 Native Tools Command Prompt for VS 2022`

If you are using vs 2019, it's the same except substitute the year, of course.

Run that shell program. Next, type `cmake --version`, and verify that cmake is at least 3.21 or greater. I am using 3.24. If you don't have it available at the command line, the next step is to add it to your path, so that it is available.

I think you have cmake now, so let's make a new directory, `c:\dev` and then cd into it.

git clone the repo into this directory, and then cd into openexr.

make a directory called build, and cd into it.

```
mkdir build
cd build
```

next, run cmake.

```
cmake .. -DCMAKE_INSTALL_PREFIX=./install
```

when it finishes, list the directory, you will see a sln file in that directory.

That file is the one to open in visual studio community.

At the top of Visual Studio find the Release build, and pick the INSTALL target.

Now, build in Visual Studio, it will take a few minutes, but when it's done, you should find the openexr libraries, includes, and binaries in c:\dev\openexr\build\install, and you should be able to run the programs in c:\dev\openexr\build\install\bin.

If you learn this pattern, you will be able to build many other open source projects that are based on cmake as well.

**Comment by lor3ny** [comment]
Thank you very much, I was able to correctly install everything needed.

I connected the include directory and lib directory to my project, but when I build the project it returns the following error.

Output:
![PSFrendering - Microsoft Visual Studio 03_06_2023 10_59_57](https://github.com/AcademySoftwareFoundation/openexr/assets/54499060/bf84914a-74d8-46d2-acf9-19a51c7307fc)


Error List:
![PSFrendering - Microsoft Visual Studio 03_06_2023 11_00_10](https://github.com/AcademySoftwareFoundation/openexr/assets/54499060/c62f9995-6c92-4129-a4fd-e5fe2f2357f4)


It appears from the error that the OpenEXR files cannot find the includes of Imath, did I make a mistake in setting up OpenEXR in VS community for my project?

**Comment by meshula** [comment]
You'll need to find where ImathBox.h is on your hard drive, and add that path to the "Include directories" section of your project settings.

**Comment by lor3ny** [comment]
I've included the libraries on the "Additional Include Path" and everything seems working. But now I've encountered a new problem, linking phase gives me an LNK2001 error:

`LNK2001	unresolved external symbol imath_half_to_float_table`

![PSFrendering - Microsoft Visual Studio 04_06_2023 10_06_50](https://github.com/AcademySoftwareFoundation/openexr/assets/54499060/0f0229ab-af14-41fc-a3ac-7be51a953738)

I've tried to look for this issue in other issue reports but I can't find a solution for VS project.

Thanks for the support that you gave to me!

**Comment by meshula** [comment]
Can I confirm that you've added the `Half` library in your project?

If it isn't that's the problem. Otherwise, read on ~

I'm sorry using OpenEXR from within Visual Studio isn't well documented. Usually people are using cmake, and that makes everything automatic. Since you are adding it manually, you also have to set the preprocessor definitions that are normally set by ImathConfig.cmake.

In this case, the use of the look up table is controlled by the preprocessor definition `IMATH_HALF_NO_LOOKUP_TABLE` so if you add that to your project's preprocessor definitions, it it should get past this problem.

**Comment by lor143n** [comment]
Thanks, now it is compiled and linked well. Thank you for your step-by-step help.

**Comment by lor3ny** [comment]
Thanks, now it is compiled and linked well. Thank you for your step-by-step help.

**Comment by meshula** [comment]
Congratulations, glad to hear it :D
