### ISSUE TITLE
try to build openexr as static universal lib on macOS Apple M1

### ISSUE THREAD

**Issue by diuming** [AcademySoftwareFoundation/openexr#1512]
I try to build on macOS Apple M1 looks like not success. 
because, there are a lot of`architecture: x86_64 file: has no symbols` messages.
How do I build static universal lib on macOS Apple M1?

cmake command with options
----
cmake \\
-DCMAKE_INSTALL_PREFIX=/mylib/universal/openexr-3.1.10 \\
-DCMAKE_BUILD_TYPE=Release \\
-DBUILD_SHARED_LIBS=OFF \\
-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \\
-S . \\
-B _build

cmake --build _build

build messages
---
[  7%] Linking CXX static library libIlmThread-3_1.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libIlmThread-3_1.a(IlmThreadSemaphore.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libIlmThread-3_1.a(IlmThreadSemaphorePosix.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libIlmThread-3_1.a(IlmThreadSemaphorePosixCompat.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libIlmThread-3_1.a(IlmThreadSemaphoreWin32.cpp.o) has no symbols
[  7%] Built target IlmThread
.
.
[ 18%] Linking C static library libOpenEXRCore-3_1.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libOpenEXRCore-3_1.a(std_attr.c.o) has no symbols
[ 18%] Built target OpenEXRCore
[ 18%] Building CXX object src/lib/OpenEXR/CMakeFiles/OpenEXR.dir/ImfAcesFile.cpp.o
.
.
.

**Comment by cary-ilm** [comment]
The "has no symbols" messages are not the problem. For this configuration, those files do, in fact, have no symbols.

I can reproduce the problem, and it almost surely is due to a mismatch in the Imath library that CMake is picking up. It's probably finding an installation of Imath that is configured inconsistently.

Add the -DOPENEXR_FORCE_INTERNAL_IMATH=ON option to your CMake, and it should resolve the problem. That will download Imath and build it internally with the same settings.

**Comment by diuming** [comment]
@cary-ilm thanks, I got it.
