### ISSUE TITLE
imf::IStream Fail to create IStream with empty filename 3.3.0 (commit: e4e6cf2)

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [AcademySoftwareFoundation/openexr#1894]
Since commit e4e6cf2eb64900c8f25414fc4b682b1b9eb370d7

i was trying to update the dependencies used inside freeimage (an image loading library) which lead to this error:
creating an imf::Stream like this: `Imf::IStream("")` will cause an error to be thrown.

This seems like a weird usage by freeimage im not really asking you to fix it as it is not hard to correct freeimage's code but its good to have it documented as a change.

**Comment by Marc-Pierre-Barbier** [comment]
Weirdly i don't believe this change affected Imf::OStream as in my testing it seems like it still works.

**Comment by kdt3rd** [comment]
huh, i would have expected that to work - I have changed input stream (not ostream just yet) to use a temporary context, but would have expected empty string ("") to work for that - null I could understand a crash due to laziness, but empty string should be ok - should have a test for that, will add and fix. There is a separate issue around mmap streams not working with said change, but this seems different, thanks...
