### ISSUE TITLE
openexr 2.3.0 static cmake build broken.

### ISSUE THREAD

**Issue by LazyDodo** [AcademySoftwareFoundation/openexr#333]
Building openexr 2.3.0 on windows , vs2015.5 , cmake 3.11.2 and with -DOPENEXR_BUILD_STATIC=ON

initially it was unhappy about the set_target_properties in IlmImfUtil/CMakeLists.txt

```
  CMake Error at IlmImfUtil/CMakeLists.txt:59 (SET_TARGET_PROPERTIES):
    SET_TARGET_PROPERTIES called with incorrect number of arguments.
```

took a quick peek, decided I'd be ok without it and took out that part out and hit
the more troublesome part.

```
  CMake Error at IlmImfUtil/CMakeLists.txt:89 (add_library):
    add_library cannot create ALIAS target "OpenEXR::IlmImfUtil_static" because
    target "IlmImfUtil_static" does not already exist.
```

and it's doesn't appear to be wrong, there is a branch for OPENEXR_BUILD_SHARED in IlmImfUtil/CMakeLists.txt to create the IlmImfUtil target but nothing to create the IlmImfUtil_static target.

**Comment by LazyDodo** [comment]
Seems like it's just the release tar.gz that is having a real bad time there, grabbing the latest from git seems to be a lot happier.

**Comment by kdt3rd** [comment]
A complete refactor of the cmake has taken place, modernizing cmake to match the "Modern CMake" guidelines and practices, we no longer have entirely custom BUILD_SHARED variables (just use the normal cmake BUILD_SHARED_LIBS), and had a major snafu in the last release with tarballs, so this should be fixed in the next release we make (if you want to test the master branch, and report any issues separately, that would be awesome). Thanks for the report!
