### ISSUE TITLE
I got an error 'expTable' was not declared in this scope

### ISSUE THREAD

**Issue by marcus70s** [AcademySoftwareFoundation/openexr#334]
Hello everybody, when I compile the libs, I got an error

Making all in config
make[1]: Entering directory '/home/marcus/Codes/openexr/openexr/OpenEXR/config'
make  all-am
make[2]: Entering directory '/home/marcus/Codes/openexr/openexr/OpenEXR/config'
make[2]: Leaving directory '/home/marcus/Codes/openexr/openexr/OpenEXR/config'
make[1]: Leaving directory '/home/marcus/Codes/openexr/openexr/OpenEXR/config'
Making all in IlmImf
make[1]: Entering directory '/home/marcus/Codes/openexr/openexr/OpenEXR/IlmImf'
make  all-am
make[2]: Entering directory '/home/marcus/Codes/openexr/openexr/OpenEXR/IlmImf'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -std=c++14 -DHAVE_CONFIG_H -I. -I../config -pthread -I/usr/local/include/OpenEXR -pthread -I.. -I../config     -pipe -g -O2 -std=c++14 -pthread -MT ImfB44Compressor.lo -MD -MP -MF .deps/ImfB44Compressor.Tpo -c -o ImfB44Compressor.lo ImfB44Compressor.cpp
libtool: compile:  g++ -std=c++14 -DHAVE_CONFIG_H -I. -I../config -pthread -I/usr/local/include/OpenEXR -pthread -I.. -I../config -pipe -g -O2 -std=c++14 -pthread -MT ImfB44Compressor.lo -MD -MP -MF .deps/ImfB44Compressor.Tpo -c ImfB44Compressor.cpp  -fPIC -DPIC -o .libs/ImfB44Compressor.o
ImfB44Compressor.cpp: In function ‘void Imf_2_3::{anonymous}::convertFromLinear(short unsigned int*)’:
ImfB44Compressor.cpp:141:9: error: ‘expTable’ was not declared in this scope
  s[i] = expTable[s[i]];
         ^
ImfB44Compressor.cpp: In function ‘void Imf_2_3::{anonymous}::convertToLinear(short unsigned int*)’:
ImfB44Compressor.cpp:149:9: error: ‘logTable’ was not declared in this scope
  s[i] = logTable[s[i]];
         ^
Makefile:813: recipe for target 'ImfB44Compressor.lo' failed
make[2]: *** [ImfB44Compressor.lo] Error 1
make[2]: Leaving directory '/home/marcus/Codes/openexr/openexr/OpenEXR/IlmImf'
Makefile:611: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/marcus/Codes/openexr/openexr/OpenEXR/IlmImf'
Makefile:506: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

any suggestions?

**Comment by KBentley57** [comment]
I am also getting a similar error with the release 2.3.0.tar.gz files.  I have built zlib and ilmbase separately.

ImfB44Compressor.cpp: In function 'void Imf_2_3::{anonymous}::convertFromLinear(short unsigned int*)':
ImfB44Compressor.cpp:141:9: error: 'expTable' was not declared in this scope
  s[i] = expTable[s[i]];
         ^~~~~~~~
ImfB44Compressor.cpp:141:9: note: suggested alternative: 'exp10l'
  s[i] = expTable[s[i]];
         ^~~~~~~~
         exp10l
ImfB44Compressor.cpp: In function 'void Imf_2_3::{anonymous}::convertToLinear(short unsigned int*)':
ImfB44Compressor.cpp:149:9: error: 'logTable' was not declared in this scope
  s[i] = logTable[s[i]];
         ^~~~~~~~
ImfB44Compressor.cpp:149:9: note: suggested alternative: 'logbl'
  s[i] = logTable[s[i]];
         ^~~~~~~~
         logbl
Makefile:799: recipe for target 'ImfB44Compressor.lo' failed

**Comment by atabakd** [comment]
Has the same issue. For now, I am opted to use v2.2.1

**Comment by jpchen** [comment]
same issue..

**Comment by fredlllll** [comment]
just wanted to say that this is still broken... release 2.3.0 aswell as master branch. both have the same error. this is on a freshly installed ubuntu 18.04

**Comment by meshula** [comment]
Quick summary: There isn’t enough information in this thread to judge, but it looks like the autoconf/make build system is what’s being attempted and failing. Also, the autoconf/make files bundled with the 2.3 tars aren’t building.

A Cmake build from top of tree github is a workaround, as it is known to work.

**Comment by fredlllll** [comment]
is there an instruction for a cmake build? i tried running it and it cant find pythonlibs or something.

**Comment by kdt3rd** [comment]
This seems it might be due to the programs that generate the various headers (including expTable for b44) being unable to find the .so they depend upon, and then failing to emit the expTable into the header (b44 uses half). The "modern cmake" refactor we have recently done fixes that for sure and the rpath is set correctly during build. The install documentation has been updated to reflect that cmake is currently the generally preferred path, but we do still support the autoconf setup.

Although the configure path is still supported and should work as well, but it may not have an appropriate rpath to locate the .so for the the generator programs, as that is traditionally a more manual process. So if you are using the autoconf / configure path, and installing ilmbase into a non-standard location (or haven't yet installed it), you may have to set LD_LIBRARY_PATH such that the b44ExpLogTable generator program can find the appropriate ilmbase dso.

Anyway, if you could give cmake a try, and report success / failure, that would be great. We are asking people to use cmake 3.12, since among other things, it has fixes for finding boost, and specifically boost::python, which we are hoping works more reliably for people. Hopefully your distribution has that version easily available at this point, but I suppose that is in itself a data point.

**Comment by KBentley57** [comment]
I have downloaded the master branch as of a few moments ago, and
everything seems to build fine for me now.  I'm using cmake 3.13, but
I suspect results to be similar for 3.12.

There seems to be a bug in the install target though.  The build
process succeeds, but using DESTDIR=/path/to/desired/directory for
make install fails.  It looks as if it's trying to create symlinks in
/usr/local/lib64 to the versioned libs, instead of
/path/to/desired/directory/usr/local/lib64 .  ex:

CMake Error: failed to create symbolic link 'libImath.so': permission denied
-- Creating symlink in /usr/local/lib64 libImath.so -> libImath-2_3.so

Setting the cmake variable CMAKE_INSTALL_PREFIX seems to work as expected.

**Comment by meshula** [comment]
CMAKE_INSTALL_PREFIX, as opposed to a custom variable such as DESTDIR is definitely a best practice.

**Comment by KBentley57** [comment]
I agree,

However, DESTDIR is, and has long been a way to last-minute change the
installation directory without recompiling the code.  It's an open
source philosophy standard, and not all that hard to implement.

https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by KBentley57** [comment]
Just to follow the last email -

It's also suggested by CMake as a way to change installation
directories.  If it doesn't work out of the box, I'd be suspect that
something else in the CMakeLists.txt need be looked at.

https://cmake.org/cmake/help/v3.12/envvar/DESTDIR.html

**Comment by meshula** [comment]
Ah, thanks for the pointers, I learned something :) The cmake docs say "it is commonly used by makefile users in order to install software at non-default location". They also say "DESTDIR may not be used on Windows because installation prefix usually contains a drive letter".

This similar issue, from USD, has a fix. 

https://github.com/davvid/USD/commit/2de4d54ce0f4939b3a57360e943bf84a31238821

It looks like they have replaced ${CMAKE_INSTALL_PREFIX} in the cmake scripts' INSTALL statements, with ${CMAKE_CURRENT_BINARY_DIR}. If that works in your case, it would be a good fix, I think.

**Comment by KBentley57** [comment]
I'll try to test that when I get a few minutes tonight.  First hand,
that looks odd, but I'll have to research it a little more.

**Comment by cary-ilm** [comment]
This should be addressed by #606, which removes the auto-generation of the headers, and moves the tables into the proper namespace. Feel free to re-open if it's still an issue.
