### ISSUE TITLE
Cmake macro `SET_ILMBASE_INCLUDE_DIRS` assumes

### ISSUE THREAD

**Issue by SylvainCorlay** [AcademySoftwareFoundation/openexr#362]
When building the static libraries for openexr, and linking with a pre-existing ilmbase (`OPENEXR_BUILD_ILMBASE=OFF`), the cmake macro `SET_ILMBASE_INCLUDE_DIRS` is still used.

It reads:
 
```cmake
MACRO(SET_ILMBASE_INCLUDE_DIRS _target)
  TARGET_INCLUDE_DIRECTORIES(${_target}
    PRIVATE ${ZLIB_INCLUDE_DIR}
    PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/../config
    [...]
  )
ENDMACRO()
```

which is wrong because it includes the headers from the source tree and not the ones specified with `ILMBASE_INCLUDE_DIR`.

**Comment by SylvainCorlay** [comment]
I came across this as I was packaging openexr for conda, and using the conda package for ilmbase.

**Comment by kdt3rd** [comment]
A complete refactor of the cmake has taken place, modernizing cmake to match the "Modern CMake" guidelines and practices, and no more global include parctices, so this should be fixed in the next release we make (if you want to test the master branch, and report any issues, that would be awesome). Thanks for the report!
