### ISSUE TITLE
Is the bootstrap/configure autotools configuration necessary?

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/openexr#492]
Calling all OpenEXR users...

The next release of OpenEXR will include a thoroughly-rewritten CMake configuration (many thanks to Kimball Thurston), and we intend this to be the preferred build tool that works consistently across Linux, macOS, and Windows, although the existing bootstrap/configure autotool configuration is still supported for Linux. We believe that the new CMake system supports all the configuration options of the existing configure scripts. 

But we're curious - who out there in the openexr-iverse regards the Gnu autotools as the configuration system of choice? We're particularly interested to hear from anyone who packages OpenEXR for distribution, or who uses any specialized configuration options.  If there are reasons that CMake is not preferred, we'd like to understand them.

Any feedback would be welcome, just comment this issue, or mail openexr-dev@lists.aswf.io, or info@openexr.com for private feedback.

**Comment by cary-ilm** [comment]
Revisiting this, we will likely retire the autotools configuration completely for the 3.0 release, leaving cmake as the sole build mechanism, consistent with other ASWF projects. If anyone would like to make a case for continuing to support building via autotools, please let us know soon. 

Are there any applications in which building OpenEXR via cmake is *not* a viable option?

**Comment by dajoke** [comment]
I wish you would just distribute straight-line compilation scripts (output by cmake?), where we could supply $(CC) $(CFLAGS) etc and have it compile. I'm not developing OpenEXR, so I don't care squat about partial builds and full makefiles. I just need to get the whole thing to compile ONCE with my tweaks --- but on several different platforms. You want cmake? What version is that? Now I have to get a version of that on each of my platforms, exactly zero of which have a standard included cmake. Call me a luddite --- I want software to have as few dependencies as possible, whether that's cmake, the latest flavor-of-the-month of C++, support libraries (ixnay on boost), you name it.... Because I'm combining OpenEXR with a bunch of OTHER software libraries, each of which have their own peculiarities and toolchains. Please, Keep It SIMPLE to use! Why are there separate IlmBase and OpenEXR portions, and SEVEN different sublibraries??? Maybe that helps development in some fashion, but it's an waste of time to developers using it. Changing OpenEXR versions is a several day job, and it shouldn't be. Thanks for reading.

**Comment by meshula** [comment]
the boostrap/configure autotools configuration is no longer part of the build system.

@dajoke Many of the issues you mention have been addressed, but not all. The build setup is simpler, and there are a reduced number of little libraries that make up OpenEXR. If there's follow up topics on build simplification, please feel free to open a new issue to discuss.
