### ISSUE TITLE
How to force Python3 build on Linux

### ISSUE THREAD

**Issue by nyue** [AcademySoftwareFoundation/openexr#611]
Hi,

  I have a Python3 build of Boost 1.70.0 and would like to build OpenEXR against that but it keeps defaulting to Python2.

  Is there a way to tell CMake to build OpenEXR specifically for Python3

```
-- Configure PyIlmBase Version: 2.4.0 Lib API: 24.0.2
-- Found Python: /home/nyue/systems/python/3.7.4/bin/python3.7 (found version "3.7.4") found components:  Interpreter Development
-- Found Python2: /sw/bin/python2.7 (found version "2.7.5") found components:  Interpreter Development
-- Found Python3: /home/nyue/systems/python/3.7.4/bin/python3.7 (found version "3.7.4") found components:  Interpreter Development
: Found Python 2.7.5 and 3.7.4
-- Found Python2 libraries: 27
-- Found Python3 libraries: 37
-- Found Boost 1.70.0 at /home/nyue/systems/boost/1.70.0-py3/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET OPTIONAL_COMPONENTS python;python2;python27;python3;python37
-- Found boost_headers 1.70.0 at /home/nyue/systems/boost/1.70.0-py3/lib/cmake/boost_headers-1.70.0
-- Found boost_python 1.70.0 at /home/nyue/systems/boost/1.70.0-py3/lib/cmake/boost_python-1.70.0
--   libboost_python37.so.1.70.0
-- Adding boost_python dependencies: headers
-- Found Boost: /home/nyue/systems/boost/1.70.0-py3/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components:  python missing components:  python2 python27 python3 python37
CMake Warning at PyIlmBase/CMakeLists.txt:104 (message):
  Ambiguous boost python module found, assuming python 2
```

Cheers

**Comment by kdt3rd** [comment]
This warning happens when the boost search is not finding boost python libraries that are tagged for a specific version of python. This used to be the way boost was configured by default (to just install "boost_python" and not have it be tied to a version of boost). This changed some time during the 1.6x series to enable both python2 and python3 to live harmoniously together. So I'm surprised your 1.70 compile doesn't have the appropriate tag applied.

One recent change I submitted a PR for but haven't merged yet, sets Boost_NO_BOOST_CMAKE, as apparently the cmake config files for at least 1.71 of boost are busted. So you might try cmake -DBoost_NO_BOOST_CMAKE=ON /path/to/src when you configure (if you're doing in the same dir, don't forget to remove the cache first or recreate the folder).

If this doesn't work, we can look at a way to change what the default maps to (python 2 vs 3)

**Comment by nyue** [comment]
Thanks, I can confirm that Boost_NO_BOOST_CMAKE did the trick for my build situation.
