### ISSUE TITLE
ImfChromaticities.cpp: Revisiting the == and != operators

### ISSUE THREAD

**Issue by arkellr** [AcademySoftwareFoundation/openexr#651]
Forgive the repetition if this may have been discussed in the past... 

Just would like to confirm that the exclusion of "white" from the == and != operators is intentional.

If so, Id like to make a PR change to the comment block that these operators apply only to the "primaries" and not the white point... otherwise if the exclusion of white is an oversight then I'd PR the change to include it. 
Personally I would hv included the white.

Let me know your thots.

**Comment by peterhillman** [comment]
I would also expect == to compare everything, even if there's a "color science" justification for it not comparing whitepoint. Perhaps the existing functionality could be implemented in a "rgbEqual()" function. There are somewhat tenuous cases where doing that comparison is useful, but it doesn't feel right that this is the behavior of ==

**Comment by meshula** [comment]
I don't know of a color science reason to not compare white as well as the primaries. It's more of a misnomer of our class I think, since the Chromaticities class is specifying a particular adaptation within the color space. Comparing the chromaticities, and the whitepoint independently, or together, is legitimate depending on context. I would prefer the == to have the C++ meaning of object equivalence, not a mysterious color-mathy interpretation. An unfortunate aspect of operator overloading, rather than having an rgbEqual() function (primariesEqual()?), is that determining where chromaticities objects are compared is going to be tedious. It would be nice to have that scrub done though, to find out if (1) we would regress anything by comparing everything and (2) if there are existing comparisons, would those comparisons be more or less correct in context with a full == operator.... sigh

**Comment by arkellr** [comment]
Thanks for all the feedback.

Ive... created PR #666 to add back "white" to the == and != ops.

**Comment by cary-ilm** [comment]
Resolved via #666.
