### ISSUE TITLE
openexr/OpenEXR_Viewers/config/LocateCg.cmake issue on Linux

### ISSUE THREAD

**Issue by etheory** [AcademySoftwareFoundation/openexr#665]
Hi there!

I've been struggling to build OpenEXR on CentOS-7.4.5 with CMake-3.14.5 due to the following:

`add_library(Cg UNKNOWN IMPORTED GLOBAL)`
and
`add_library(CgGL UNKNOWN IMPORTED GLOBAL)`

only get correctly added if I change them to:

`add_library(Cg SHARED IMPORTED GLOBAL)`
and
`add_library(CgGL SHARED IMPORTED GLOBAL)`

otherwise I get the error:

> NOTICE-- Found Cg library
> CMake Error at OpenEXR_Viewers/config/LocateCg.cmake:27 (add_library):
>   add_library cannot create ALIAS target "Cg::Cg" because target "Cg" is not
>   a library.
> Call Stack (most recent call first):
>   OpenEXR_Viewers/CMakeLists.txt:47 (include)

For both Cg and CgGL

Which appears to be thrown by:
`add_library(Cg::Cg ALIAS Cg)`
and
`add_library(Cg::CgGL ALIAS CgGL)`

When their target type is 

> UNKNOWN

Are you aware of this issue and is there anything I can do about it aside from hacking the CMake?

Thanks,
Luke

**Comment by fnaum** [comment]
I think that was fixed in `cmake-3.15.0`
https://gitlab.kitware.com/cmake/cmake/issues/18327
https://gitlab.kitware.com/cmake/cmake/merge_requests/3148
I did not try that version, but updating to 3.16.4 did the trick.

So I guess you'll need `cmake_minimum_required(VERSION 3.15)` [here](https://github.com/AcademySoftwareFoundation/openexr/blob/master/CMakeLists.txt#L10)

**Comment by etheory** [comment]
Thanks @fnaum!
