### ISSUE TITLE
Using the example Chromacity files - issue with chromaticities

### ISSUE THREAD

**Issue by darkyellow** [AcademySoftwareFoundation/openexr#686]
I am trying to read the some images with Chromaticities in so I can process them correctly.

In the example images that you can download from github there is a Chromaticities folder with Rec709.exr and XYZ.exr. These should display the same.

The XYZ file has chromaticities provided, the head has this info in

file format version: 2, flags 0x0
channels (type chlist):
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
chromaticities (type chromaticities):
    red   (1 0)
    green (0 1)
    blue  (0 0)
    white (0.333333 0.333333)
compression (type compression): piz
dataWindow (type box2i): (0 0) - (609 405)
displayWindow (type box2i): (0 0) - (609 405)
lineOrder (type lineOrder): increasing y
owner (type string): "Copyright 2006 Industrial Light & Magic"
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
type (type string): "scanlineimage"

When I use the XYZtoRGB function with a Y value of 1 the matrix returned is the identity matrix (some minor rounding issues but it basically is). If I convert XYX values to RGB I basically get yellowy petals which is the same as doing no conversion. GIMP produces the same image. 

Are the Chromatic values correct here?

**Comment by peterhillman** [comment]
Hi @darkyellow.
To display OpenEXR images correctly, you must convert from the file chromaticities to your display's chromaticities. The matrix to do that conversion is given by
`RGBtoXYZ( inputChromaticities , 1.0 ) * XYZtoRGB( outputChromaticities , 1.0 )`
where `inputChromaticities` are the file chromaticities and `outputChromaticities` are the display chromaticities.
If I apply that transform to both Rec709.exr and XYZ.exr, the pictures look the same. Treating the display as Rec709 (the default value for Chromaticities) gives an identity matrix for the Rec709.exr image in this case.

When combined multiple files which have different chromaticities, you should conform them all to the same chromaticities, as your "working space". You may then do a second conversion to the display's chromaticities to display your output correctly. 

The example files may be a little misleading, because the XYZ in `RGBtoXYZ` and `XYZtoRGB` is merely a transitional space to join the two matrices together, but it happens that one of the example files is in XYZ space.

**Comment by cary-ilm** [comment]
Assuming this resolves the issue for now, but feel free to reopen or post another question if you'd like to continue the discussion.

**Comment by wkjarosz** [comment]
@peterhillman @cary-ilm: I ran into something related to this issue, and figured it better to leave a comment here than to start a new issue.

I'm puzzled why the "correct way" to display EXR files ignores any potential difference between the source and target white points. I would have expected that sandwiching the RGBtoXYZ matrices with a chromatic adaptation matrix (e.g. from von Kries, XYZ scaling, or Bradford adaptation methods) would be the correct answer. However, doing so makes these Rec790 and XYZ test images mismatch slightly.

In fact, OpenEXR's own `AcesInputFile::Data::initColorConversion` function does include a Bradford matrix when converting to an Aces file. Why is that not the correct approach in this case?

Thanks

**Comment by peterhillman** [comment]
Just my view, but...
The ACES standard specifies Bradford adaptation, so that is required when converting images to ACES colorspace by definition.

OpenEXR itself doesn't specify whether or how to do adaptation, it merely provides metadata to indicate the image state. The method of adaptation or white balancing may well be specified by a larger system of which OpenEXR is a part, ACES being one such specification. So if OpenEXR attempted to define when and how to apply adaptation, it may conflict with other specifications.

Arguably, XYZ.exr's  (1/3, 1/3) white point is a 'hack' [in the standard](https://openexr.com/en/latest/TechnicalIntroduction.html#cie-xyz-color) to allow XYZ images to be encoded as RGB images, and to indicate that with the `chromaticities` attribute. That white is not intended to be the color coordinate that will be used to display neutral colors. It doesn't make sense to me to apply adaptation in this case. In general, OpenEXR specifies the intended neutral color with the `adoptedNeutral` [standard attribute](https://openexr.com/en/latest/StandardAttributes.html#encoded-image-color-characteristics), and that may be different to the `chromaticities` white point. In the absence of other rules, it seems logical to me that adaptation would be applied when converting the image to a different adoptedNeutral, but not when converting the image chromaticities. Unfortunately, the XYZ.exr image doesn't have an `adoptedNeutral` and the documentation doesn't discuss what to do if it is missing.

It seems the `chromaticities` attribute is rarely used in OpenEXR images, and is often incorrect, so it may be safer to ignore it altogether. This is partly because OpenColorIO is widely used for color management, and doesn't have a mechanism for working with chromaticities, so it is hard to store correct values. There is discussion about replacing the `chromaticities` attribute with something that's more compatible with OpenColorIO but still meaningful without an OpenColorIO managed pipeline, which should help to clarify this sort of thing, and make this discussion a moot point.

**Comment by meshula** [comment]
OCIO/Nanocolor is the direction we (the OCIO nanocolor team ;) ) would like to promote for OpenEXR. Nanocolor provides a simple, and strongly defined set of color spaces with no ambiguity of interpretation. I'd suggest we rehabilitate the chromaticities and related field in an OpenEXR file to operate as per the nanocolor spec, and additionally that we defer to a standard nanocolor named color space via s string if supplied.

nanocolor https://www.youtube.com/watch?v=ym1kfYmGz-M

The color interop forum also has a whitepaper laying out the nancolor spaces in great detail. The draft final is here: https://docs.google.com/document/d/1IV3e_9gpTOS_EFYRv2YGDuhExa4wTaPYHW1HyV36qUU

**Comment by wkjarosz** [comment]
Thanks @peterhillman @meshula for your insights.

It might make sense to explicitly state, in the documentation/readme associated with that folder of test images, that the correct way to interpret the values in the file is to convert to XYZ and then from XYZ to the target space while ignoring whitepoint (but only ignore the whitepoint for XYZ images?).

While we are discussing this, I'd like to also understand better...

- In all the literature I'm familiar with, a color space is defined with respect to a reference illuminant/whitepoint, and converting to another color space requires accounting not only for the primaries of each space, but also the white points of those spaces. If adoptedNeutral is the intended attribute for defining the chromatic adaptation step, then what is the purpose of the white point value in the chromaticities attribute at all? (I realize this may be a moot point if no one even uses this attribute correctly anyway).

- Can you clarify why you would view XYZ's white points as a hack? The values of 1/3,1/3 simply correspond to the E standard illuminant. Why should this be viewed differently than the whitepoint of some RGB color space? (This might be due to my confusion about what the whitepoint attribute is even used for in the presence of adoptedNeutral).

**Comment by meshula** [comment]
My advice is in contradiction to Peter's perhaps. nanocolor defines a color space with respect to chromaticities and whitepoint, and a transfer function and we follow RP177-1993 in not using adaptation, but simply an affine transform derived from chr/wp. https://github.com/meshula/Nanocolor/blob/d1282fc26e5e18ed9a67b7a2bf72627dcffcd7d4/nanocolor.c#L439 RP177-1993 expects the 1/3 illuminant, so isn't a hack from that perspective.

This formulation gives numerically identical results to OCIO for ACES conversions to and from D65 based color spaces, and so further adaptation isn't necessary for the subset of color spaces that can be described via basic colorimetry.

For anything more sophisticated, I believe the recommendation would be to associate an OCIO conf or CTL file with the exr data instead.

**Comment by meshula** [comment]
OpenEXR's use of adopted neutral versus whitepoint is vexing. It effectively means white point, but is worded to suggest adaptation. adopted neutral is an XY coordinate that should be rendered to equal values under a different whitepoint. Not specifying the whitepoint in EXR sets up an impossible situation. since you can't know WHAT you are adapting to that coordinate. So the 1/3 hack Peter mentions is to implicitly assume Illuminant E. So I guess I am agreeing with Peter.

Adapted whitepoint has no place in a scene referred EXR image because the adapted whitepoint is talking about a color rendering operation to which the EXR file is merely an input. EXR should stick to colorimetry, and not involve itself in "color balance" operations.

Sorry @wkjarosz , this doesn't really help, but I'm not happy with EXR's treatment of color, nor am I happy with "famous NLE broke color in EXR decades ago by mis-reading the ACES spec so it can't be fixed." "famous NLE" has been fixed many many years ago.

**Comment by peterhillman** [comment]
Well I wish I understood color adaptation better than I do, and maybe I'm just confusing matters, but @meshula's explanation seems to make sense to me, and doesn't contradict my understanding as such.

@meshula you say:
> adopted neutral is an XY coordinate that should be rendered to equal values under a different whitepoint

The spec says this:

> Specifies the CIE (x,y) coordinates that should be considered neutral during color rendering. Pixels in the image file whose (x,y) coordinates match the adoptedNeutral value should be mapped to neutral values on the display.

For scene referred images, that definition mentioning a display does seem out of place. However, it doesn't explicitly say "neutral values" are those that have equal RGB values in this image. Perhaps `adoptedNeutral` allows for image pipelines which carry images through different colorspaces, to track what color will finally end up as "looking neutral" when viewed, without applying adaptation every time an image is converted.  In that case, adoptedNeutral and chromaticities.white would be different. 

Contrived example: suppose an image is displayed on an HDR monitor configured to DCI-P3 primaries with the D65 whitepoint. A second monitor is added directly alongside it and needs to display identical imagery, but it's locked to a space with a different whitepoint. To get the second monitor to look the same as the first, you must convert the image you are displaying between the two chromaticities, but should not apply adaptation: you don't want (1,1,1) on one monitor to display as (1,1,1) on the other, because those are different colors. If the first monitor is displaying (1,1,1), that means "D65". So, the second monitor needs to be sent the RGB value that corresponds to the D65 whitepoint in its colorspace. You might well consider the 'adoptedNeutral' of the image converted for the second monitor to remain D65, but the chromaticities whitepoint would match that monitor's different whitepoint.

With regard to XYZ images and what I rashly called a "hack":

I think of the 'white' in the chromaticities as merely a mechanism for technical encoding of the colorspace. Chromaticities store red,green and blue values with normalized (x,y) coordinates, so the intensities of each are not known. Different white points can be obtained from the same (x,y) coordinates of the red, green and blue primaries by scaling the relative intensity of each. Encoding the white point (x,y) allows those relative intensities to be derived, which is exactly what OpenEXR's RGBtoXYZ does.

The color space could instead be defined with absolute (X,Y,Z) values for red, green and blue only. "white" would be the sum of all three. Then, an XYZ image stored in RGB channels would have its space tagged as "red=(1,0,0) green=(0,1,0) blue=(0,0,1)". As we need to store chromaticities instead, we compute white, which is (1,1,1), normalize each to get (x,y,z) then drop z, so tagging the image as "red=(1,0) green=(0,1) blue=(0,0) white=(1/3,1/3)". Under that interpretation, storing (1/3,1/3) for white is a way to make sure that the RGBtoXYZ matrix is an identity matrix, and it does feel a little weird to me, but I don't think it's wrong. (1/3,1/3) happens to be illuminant E, but that's "just" because that's how CIE-XYZ space is defined.

**Comment by wkjarosz** [comment]
Thanks both for the continued discussion -- I also wish I understood this better, and this (I think) helps.

The fact that EXR is scene referred is a good reminder. I think I may not realize just how many concepts from color spaces I have to think about differently (or entirely ignore) compared to output referred.

I think the ultimate take-home message for me is that for practical purposes I probably shouldn't waste my time getting hung up on how to interpret the chromaticities in exr files since they are often wrong, and there is genuine confusion on how they should be used -- until there is a better system in place that is.

**Comment by wkjarosz** [comment]
Also, @peterhillman I had never thought of whitepoint as providing the mechanism to convert from relative xy to absolute XYZ coordinates. This of course makes perfect sense. Thanks for that perspective.

**Comment by meshula** [comment]
Hey folks! The Color Interop Forum has kindly volunteered to attend the next OpenEXR TSC meeting to talk through colorimetry in OpenEXR and also to explore ideas around how we might work together.

**Comment by lgritz** [comment]
I would sure love for us to definitively choose and reserve a metadata name for the color space and document that we expect that if an exr file contains it and it's one of the CIF's reserved names, it should be considered the source of truth for that file.
